--IDPK DAS TABELAS SÃO GERADAS ATRAVÉS DE SEQUENCES

--CADASTROS E ALTERAÇÕES

--CADASTRAR UM USUÁRIO
INSERT INTO USUARIO 
  (USU_IDPK, USU_NOME, USU_DATA_NASCIMENTO, USU_GENERO, USU_EMAIL, USU_SENHA) VALUES
  (USU_IDPK_SEQ.NEXTVAL, '[NOME DO USUÁRIO]', TO_DATE ('[DATA DE NASCIMENTO]', 'DD/MM/YYYY'), [GENERO DO USUARIO], '[EMAIL DE ACESSO]', '[SENHA DE ACESSO]');

--ALTERAÇÃO DOS DADOS DO USUÁRIO, UTILIZANDO SEU IDPK COMO REFERENCIA.
UPDATE USUARIO SET USU_NOME = '[NOME DO USUÁRIO]', USU_DATA_NASCIMENTO = TO_DATE ('[DATA DE NASCIMENTO]', 'DD/MM/YYYY'),
  USU_GENERO = [GENERO DO USUARIO], USU_EMAIL = '[EMAIL DE ACESSO]', USU_SENHA = '[SENHA DE ACESSO]'
  WHERE USU_IDPK = [IDPK DO USUÁRIO];


-- PARA CASO FOR PREENCHER CATEGORIAS EM UM RECEBIMENTO OU GASTO, É NECESSÁRIO PRIMEIRO CADASTRAR
INSERT INTO CATEGORIA 
  (CAT_IDPK, CAT_USUARIO_IDPK, CAT_NOME) VALUES
  (CAT_IDPK_SEQ.NEXTVAL, [IDPK DO USUÁRIO], '[NOME DA CATEGORIA]');


  --CADASTRAR AS RECEITAS/RECEBIMENTOS DO USUÁRIO
INSERT INTO RECEBIMENTO 
  (REC_IDPK, REC_USUARIO_IDPK, REC_CATEGORIA_IDPK, REC_VALOR, REC_DATA, REC_DESCRICAO) VALUES
  (REC_IDPK_SEQ.NEXTVAL, [IDPK DO USUÁRIO], [IDPK DA CATEGORIA], [VALOR DO RECEBIMENTO], TO_DATE ('[DATA DO RECEBIMENTO]', 'DD/MM/YYYY'), '[DESCRICAO]');

  --ALTERAR TODOS OS DADOS DAS RECEITAS DO USUÁRIO, UTILIZANDO O SEU IDPK COMO REFERENCIA
UPDATE RECEBIMENTO SET REC_USUARIO_IDPK = [IDPK DO USUÁRIO], REC_CATEGORIA_IDPK = [IDPK DA CATEGORIA], 
  REC_VALOR = [VALOR DO PRODUTO], REC_DATA = TO_DATE ('[DATA DO RECEBIMENTO]', 'DD/MM/YYYY'), REC_DESCRICAO = '[DESCRICAO]'
  WHERE REC_IDPK = [IDPK DO RECEBIMENTO];

  --CADASTRAR AS DESPESAS/GASTOS DO USUÁRIO
INSERT INTO GASTO
  (GAS_IDPK, GAS_USUARIO_IDPK, GAS_CATEGORIA_IDPK, GAS_VALOR, GAS_DATA, GAS_DESCRICAO) VALUES
  (GAS_IDPK_SEQ.NEXTVAL, [IDPK DO USUÁRIO], [IDPK DA CATEGORIA], [VALOR DO GASTO], TO_DATE ('[DATA DO GASTO]', 'DD/MM/YYYY'), '[DESCRICAO]');

  --ALTERAR TODOS OS DADOS DOS GASTOS DO USUÁRIO, UTILIZANDO O SEU IDPK COMO REFERENCIA
UPDATE GASTO SET GAS_USUARIO_IDPK = [IDPK DO USUÁRIO], GAS_CATEGORIA_IDPK = [IDPK DA CATEGORIA], 
  GAS_VALOR = [VALOR DO GASTO], GAS_DATA = TO_DATE ('[DATA DO GASTO]', 'DD/MM/YYYY'), GAS_DESCRICAO = '[DESCRICAO]'
  WHERE GAS_IDPK = [IDPK DO GASTO];


-- PARA CADASTRAR UM INVESTIMENTO, É NECESSÁRIO ANTES CADASTRAR UM BANCO E O TIPO DE INVESTIMENTO
INSERT INTO BANCO 
  (BAN_IDPK, BAN_USUARIO_IDPK, BAN_NOME) VALUES
  (BAN_IDPK_SEQ.NEXTVAL, [IDPK DO USUÁRIO], '[NOME DO BANCO]');

INSERT INTO TIPO_INVESTIMENTO 
  (TIN_IDPK, TIN_USUARIO_IDPK, TIN_NOME) VALUES
  (TIN_IDPK_SEQ.NEXTVAL, [IDPK DO USUÁRIO], '[NOME DO TIPO DE INVESTIMENTO]');


  --CADASTRAR OS INVESTIMENTOS DO USUÁRIO
INSERT INTO INVESTIMENTO
  (INV_IDPK, INV_USUARIO_IDPK, INV_TIPO_IDPK, INV_BANCO_IDPK, INV_NOME, INV_VALOR, INV_DATA_INVESTIMENTO, INV_DATA_VENCIMENTO) VALUES
  (INV_IDPK_SEQ.NEXTVAL, [IDPK DO USUÁRIO], [IDPK DO TIPO DE INVESTIMENTO], [IDPK DO BANCO], '[NOME DO INVESTIMENTO]', 
    [VALOR INVESTIDO], TO_DATE ('[DATA DO INVESTIMENTO]', 'DD/MM/YYYY'), TO_DATE ('[DATA DO VENCIMENTO]', 'DD/MM/YYYY'));

  --ALTERAR TODOS OS DADOS DOS GASTOS DO USUÁRIO, UTILIZANDO O SEU IDPK COMO REFERENCIA
UPDATE INVESTIMENTO SET INV_USUARIO_IDPK = [IDPK DO USUÁRIO], INV_TIPO_IDPK = [IDPK DO TIPO DE INVESTIMENTO], 
  INV_BANCO_IDPK = [IDPK DO BANCO], INV_NOME = '[NOME DO INVESTIMENTO]', INV_VALOR = [VALOR INVESTIDO], 
  INV_DATA_INVESTIMENTO = TO_DATE ('[DATA DO INVESTIMENTO]', 'DD/MM/YYYY'), INV_DATA_VENCIMENTO = TO_DATE ('[DATA DO VENCIMENTO]', 'DD/MM/YYYY')
  WHERE INV_IDPK = [IDPK DO INVESTIMENTO];


--CONSULTAS

--CONSULTAR OS DADOS DE UM USUÁRIO (FILTRAR A PARTIR DO SEU IDPK)
SELECT * FROM USUARIO WHERE USU_IDPK = [IDPK DO USUÁRIO];

--Consultar os dados de um único registro de despesa de um usuário 
--(filtrar a partir do IDPK do usuário e do IDPK da despesa).
SELECT * FROM GASTO WHERE GAS_USUARIO_IDPK = [IDPK DO USUÁRIO] AND GAS_IDPK = [IDPK DO GASTO];

--Consultar os dados de todos os registros de despesas de um usuário, 
--ordenando-os dos registros mais recentes para os mais antigos (filtrar a partir do seu IDPK).
SELECT * FROM GASTO WHERE GAS_USUARIO_IDPK = [IDPK DO USUÁRIO] ORDER BY GAS_IDPK DESC;

--Consultar os dados de um único registro de investimento de um usuário 
--(filtrar a partir do IDPK do usuário e do IDPK de investimento).
SELECT * FROM INVESTIMENTO WHERE INV_USUARIO_IDPK = [IDPK DO USUÁRIO] AND INV_IDPK = [IDPK DO INVESTIMENTO];

--Consultar os dados de todos os registros de investimentos de um usuário, 
--ordenando-os dos registros mais recentes para os mais antigos (filtrar a partir do seu IDPK).
SELECT * FROM INVESTIMENTO WHERE INV_USUARIO_IDPK = [IDPK DO USUÁRIO] ORDER BY INV_IDPK DESC;

--Consultar os dados básicos de um usuário, o último investimento registrado e a
--última despesa registrada (filtrar a partir do IDPK de usuário – consulta 
--necessária para o dashboard. Dica: veja consulta com junções).
SELECT * FROM USUARIO u
LEFT OUTER JOIN INVESTIMENTO i ON i.INV_IDPK = 
  (SELECT MAX(i2.INV_IDPK) FROM INVESTIMENTO i2 WHERE i2.INV_USUARIO_IDPK = u.USU_IDPK)
LEFT OUTER JOIN GASTO g ON g.GAS_IDPK = 
  (SELECT MAX(g2.GAS_IDPK) FROM GASTO g2 WHERE g2.GAS_USUARIO_IDPK = u.USU_IDPK)
WHERE u.USU_IDPK = [USUARIO_IDPK];
