SET SERVEROUTPUT ON;
DECLARE
	V_NOTA_FINAL CHAR(1) := 'B';
BEGIN
	CASE V_NOTA_FINAL
		WHEN 'A' THEN DBMS_OUTPUT.PUT_LINE('EXCELENTE');
		WHEN 'B' THEN DBMS_OUTPUT.PUT_LINE('MUITO BOM...');
		WHEN 'C' THEN DBMS_OUTPUT.PUT_LINE('BOM');
		WHEN 'D' THEN DBMS_OUTPUT.PUT_LINE('INSUFICIENTE');
		WHEN 'F' THEN DBMS_OUTPUT.PUT_LINE('REPROVADO');
	ELSE 
		DBMS_OUTPUT.PUT_LINE('FORA DA FAIXA...!');
	END CASE;
END;