-- A instrução SQL abaixo trata do tema LOOP simples em Oracle PL/SQL.
SET SERVEROUTPUT ON;
DECLARE
	V_CONTADOR NUMBER(1) := 00;
BEGIN
	LOOP
		V_CONTADOR := V_CONTADOR + 1;
		DBMS_OUTPUT.PUT_LINE('CONTADOR NÚMERO(' || V_CONTADOR || ')' );
		-- SE O VALOR DO CONTADOR ULTRAPASSAR O NÚMERO 6, O PROCESSAMENTO SE ENCERRA.
		IF V_CONTADOR > 6 THEN
			EXIT;
		END IF;
	END LOOP;
	DBMS_OUTPUT.PUT_LINE('SAÍMOS DO LOOP => CONTADOR NÚMERO(' || V_CONTADOR || ')' );
END;