CREATE OR REPLACE FUNCTION FUN_DB_CALC_VL_COMISSAO_FUNC_DIA(
P_NR_MATRICULA_FUNC_LOJA IN DB_FUNC_LOJA.NR_MATRICULA_FUNC_LOJA%TYPE,
P_DT_PEDIDO IN DATE) RETURN NUMBER
IS
	-- VARIÁVEL DO TIPO DE DADO DA COLUNA, POIS VAMOS RETORNAR O % DE COMISSÃO 
	-- PAGA PARA UM DETERMINADO FUNCIONARIO
    V_VL_PERC_COMISSAO DB_FUNC_LOJA.VL_PERC_COMISSAO%TYPE;
	-- VARIÁVEL QUE IRÁ RECEBER O VALOR TOTAL DE VENDA DO DIA DE TRABALHO DO FUNCIONARIO
	V_VL_TOT_VENDA NUMBER;
	-- VARIÁVEL QUE IRÁ CALCULAR A COMISSÃO QUE O FUNCIONÁRIO IRÁ RECEBER NO FINAL DO DIA.
	V_VL_TOT_COMISSAO_DIA NUMBER := 00;
BEGIN
	
	BEGIN

		SELECT  VL_PERC_COMISSAO
		INTO	V_VL_PERC_COMISSAO
		FROM    DB_FUNC_LOJA
		WHERE   NR_MATRICULA_FUNC_LOJA = P_NR_MATRICULA_FUNC_LOJA;

   		-- EXIBE O VALOR DA VENDA DO DIA PARA DETERMINADO FUNCIONÁRIO.
		DBMS_OUTPUT.PUT_LINE('O FUNCIONARIO COM A MATRÍCULA(' || P_NR_MATRICULA_FUNC_LOJA || ') POSSUI O VALOR DE COMISSÃO EM:' || V_VL_PERC_COMISSAO);

		-- ENCONTRAMOS O FUNCIONÁRIO, E AGORA VAMOS CALCULAR
		-- O VALOR TOTAL QUE ELE VENDEU EM UM DETERMINADO DIA DE TRABALHO
		SELECT 	SUM(VL_TOT_PEDIDO) 
		INTO	V_VL_TOT_VENDA
		FROM    DB_PEDIDO
        WHERE   NR_MATRICULA_FUNC_ATD = P_NR_MATRICULA_FUNC_LOJA
        AND		TRUNC(DT_PEDIDO) = P_DT_PEDIDO;
		
   		-- EXIBE O VALOR DA VENDA DO DIA PARA DETERMINADO FUNCIONÁRIO.
		DBMS_OUTPUT.PUT_LINE('O FUNCIONARIO COM A MATRÍCULA(' || P_NR_MATRICULA_FUNC_LOJA || ') POSSUI O VALOR TOTAL DE VENDA EM:' || V_VL_TOT_VENDA);

		IF V_VL_TOT_VENDA IS NULL THEN
			V_VL_TOT_VENDA := 00;
		ELSE
			-- CALCULO DO VALOR TOTAL DE COMISSÃO QUE O FUNCIONÁRIO TEM DIREITO A RECEBER
			V_VL_TOT_COMISSAO_DIA := ROUND( V_VL_TOT_VENDA * (V_VL_PERC_COMISSAO/100),2);
		END IF;
		
		-- EXIBE OS DADOS DO FUNCIONÁRIO E O VALOR DA COMISSÃO CALCULADO.
		DBMS_OUTPUT.PUT_LINE('O FUNCIONARIO COM A MATRÍCULA(' || P_NR_MATRICULA_FUNC_LOJA || ') POSSUI O VALOR DE COMISSÃO:' || V_VL_TOT_COMISSAO_DIA);
        
	EXCEPTION
		-- SE NÃO ENCONTRAR O FUNCIONÁRIO, NÃO PRECISA CALCULAR.
		WHEN NO_DATA_FOUND THEN
			V_VL_PERC_COMISSAO := 00;
			DBMS_OUTPUT.PUT_LINE('O FUNCIONARIO COM A MATRÍCULA(' || P_NR_MATRICULA_FUNC_LOJA || ') NÃO ESTÁ CADASTRADO!');
	END;
    
    --RETORNA O VALOR DA COMISSÃO DIÁRIA DO FUNCIONARIO.
    RETURN V_VL_TOT_COMISSAO_DIA;
END FUN_DB_CALC_VL_COMISSAO_FUNC_DIA;

-- SOLICITAMOS QUE SEJA EXIBIDO O VALOR TOTAL DE COMISSÃO
-- DO CLIENTE DE NÚMERO 283 PARA O DIA 21/12/2024.
COLUMN FUN_DB_CALC_VL_COMISSAO_FUNC_DIA(283) FORMAT A30;
SET SERVEROUTPUT ON;
SELECT FUN_DB_CALC_VL_COMISSAO_FUNC_DIA(283, TO_DATE('21/12/2024','DD/MM/YYYY') ) FROM DUAL;


--
-- VERIFICA SE TEMOS VENDAS FEITAS POR UM DETERMINADO FUNCIONARIO
--
SELECT  NR_MATRICULA_FUNC_ATD,
		DT_PEDIDO,
        SUM(VL_TOT_PEDIDO) 
FROM    DB_PEDIDO
-- WHERE   NR_MATRICULA_FUNC_ATD = 283
GROUP BY NR_MATRICULA_FUNC_ATD,
		DT_PEDIDO
ORDER BY 2 DESC;